#!/usr/bin/env Rscript

# Builds cv/cv.tex from _data/cv.yml plus the site's own collections.
#
#   Rscript cv/build_cv.R && latexmk -pdf -cd cv/cv.tex && cp cv/cv.pdf files/cv.pdf
#
# Hand-written sections (education, skills, service, ...) live in _data/cv.yml.
# Working papers, teaching, and talks are read from _papers/, _teaching/, and
# _talks/ so the CV and the website can never disagree about them.
#
# Deliberately linear and repetitive: one function per section, no cleverness.
# If it breaks, cv/cv.tex is committed and still compiles on its own.

library(yaml)

`%||%` <- function(a, b) if (is.null(a) || length(a) == 0) b else a

# Resolve the repo root whether run from the repo or from cv/.
root <- if (dir.exists("_data")) "." else ".."


# ---- helpers ---------------------------------------------------------------

# Escape characters that are syntax in LaTeX, and turn typographic characters
# into their TeX equivalents. Order matters: backslash first, then the rest.
tex_escape <- function(x) {
  if (length(x) == 0) return(character(0))
  x <- as.character(x)
  x <- gsub("\\", "\\textbackslash{}", x, fixed = TRUE)
  for (ch in c("&", "%", "$", "#", "_", "{", "}")) {
    x <- gsub(ch, paste0("\\", ch), x, fixed = TRUE)
  }
  x <- gsub("~", "\\textasciitilde{}", x, fixed = TRUE)
  x <- gsub("^", "\\textasciicircum{}", x, fixed = TRUE)
  # Typographic characters -> TeX
  x <- gsub("\u2019", "'", x)          # right single quote
  x <- gsub("\u2018", "`", x)
  x <- gsub("\u201C", "``", x)         # left double quote
  x <- gsub("\u201D", "''", x)
  x <- gsub("\u2014", "---", x)
  x <- gsub("\u2013", "--", x)
  # Straight double quotes -> curly, alternating open/close.
  # Done by character position: strsplit() drops trailing empty fields, which
  # silently ate the closing quote on any string ending in ".
  x <- vapply(x, function(s) {
    pos <- gregexpr('"', s, fixed = TRUE)[[1]]
    if (pos[1] == -1) return(s)
    chars <- strsplit(s, "", fixed = TRUE)[[1]]
    for (i in seq_along(pos)) {
      chars[pos[i]] <- if (i %% 2 == 1) "``" else "''"
    }
    paste0(chars, collapse = "")
  }, character(1), USE.NAMES = FALSE)
  # Ranges read better as en-dashes: 2021-2023, 2024-Present
  x <- gsub("(\\d)-(\\d)", "\\1--\\2", x)
  x <- gsub("(\\d)-([A-Z])", "\\1--\\2", x)
  x
}

# Wrap a title in TeX quotes. `period = TRUE` puts the stop inside the quotes.
quoted <- function(x, period = FALSE) {
  paste0("``", tex_escape(x), if (period) "." else "", "''")
}

# Keep an entry from splitting across a page break. \needspace forces the whole
# block onto the next page if it won't fit; the samepage environment alone only
# adjusts penalties and still let two-line teaching entries split.
samepage <- function(x, lines = 3) {
  paste0("\\needspace{", lines, "\\baselineskip}\n",
         "\\begin{samepage}\n", x, "\n\\end{samepage}\n")
}

# Read the YAML front matter block from a Jekyll markdown file.
# Returns list(meta = <parsed yaml>, body = <character vector of body lines>).
read_front_matter <- function(path) {
  lines <- readLines(path, warn = FALSE, encoding = "UTF-8")
  fences <- which(trimws(lines) == "---")
  if (length(fences) < 2 || fences[1] != 1) {
    stop("No front matter found in ", path)
  }
  meta <- yaml.load(paste(lines[(fences[1] + 1):(fences[2] - 1)], collapse = "\n"))
  body <- if (fences[2] < length(lines)) lines[(fences[2] + 1):length(lines)] else character(0)
  list(meta = meta, body = body)
}

collection <- function(dir) {
  paths <- list.files(file.path(root, dir), pattern = "\\.md$", full.names = TRUE)
  lapply(paths, function(p) c(read_front_matter(p), list(path = p)))
}

# Sort a list of entries by their front-matter date, newest first.
by_date_desc <- function(entries) {
  d <- vapply(entries, function(e) as.character(e$meta$date %||% "0000-01-01"), character(1))
  entries[order(as.Date(d), decreasing = TRUE)]
}

section <- function(name) paste0("\n\\section*{", tex_escape(name), "}\n")

itemize <- function(items) {
  if (length(items) == 0) return("")
  paste0(
    "\\begin{itemize}\n",
    paste0("  \\item ", items, collapse = "\n"),
    "\n\\end{itemize}\n"
  )
}


# ---- load data -------------------------------------------------------------

# NOT _data/cv.yml -- Jekyll would collapse that into the same site.data.cv key
# as the academicpages placeholder _data/cv.json, and the JSON wins.
cv <- read_yaml(file.path(root, "_data", "cv_sections.yml"))

out <- character(0)
add <- function(...) out <<- c(out, ...)


# ---- preamble --------------------------------------------------------------
# Lifted from CV_real/2025-10-02_auten_cv.qmd -- this is the look being matched.

add(
  "% Generated by cv/build_cv.R -- do not edit by hand.",
  "% Source: _data/cv.yml plus _papers/, _teaching/, _talks/",
  "\\documentclass[letterpaper,11pt]{article}",
  "\\usepackage[top=0.5in,bottom=0.5in,left=0.5in,right=0.5in]{geometry}",
  "\\usepackage{enumitem}",
  "\\setlist[itemize]{noitemsep, topsep=0pt, partopsep=0pt, parsep=0pt, leftmargin=*}",
  "\\setlength{\\parindent}{0pt}",
  "\\setlength{\\parskip}{6pt}",
  "% Section headings in small caps with a horizontal rule",
  "\\usepackage{needspace}",
  "\\usepackage{titlesec}",
  "\\titleformat{\\section}{\\large\\scshape}{}{0em}{}[\\titlerule]",
  "\\titlespacing*{\\section}{0pt}{12pt}{4pt}",
  "\\usepackage[hidelinks]{hyperref}",
  "\\pagestyle{plain}",
  "\\begin{document}",
  ""
)


# ---- header ----------------------------------------------------------------

b <- cv$basics
add(
  "\\begin{center}",
  paste0("{\\large ", tex_escape(b$name), "}\\\\"),
  paste0("\\href{mailto:", b$email, "}{", tex_escape(b$email), "}"),
  paste0("\\textbar{} \\href{", b$github, "}{GitHub}"),
  paste0("\\textbar{} \\href{", b$website, "}{Website}"),
  paste0("\\textbar{} ", tex_escape(b$location)),
  "\\end{center}",
  "\\hrule",
  "\\vspace{8pt}",
  ""
)


# ---- education -------------------------------------------------------------

add(section("Education"))
for (e in cv$education) {
  det <- tex_escape(unlist(e$detail))
  add(samepage(paste0(
    "\\textbf{", tex_escape(e$institution), "}, ", tex_escape(e$location), "\\\\\n",
    "\\textit{", tex_escape(e$degree), "}, ", tex_escape(e$dates), "\\\\\n",
    paste(det, collapse = "\\\\\n")
  )))
}


# ---- working papers (from _papers/) ----------------------------------------

papers <- by_date_desc(collection("_papers"))
add(section("Working Papers"))
add(itemize(vapply(papers, function(p) quoted(p$meta$title), character(1))))


# ---- conference presentations (from _talks/) -------------------------------

talks <- by_date_desc(collection("_talks"))
if (length(talks) > 0) {
  add(section("Conference Presentations"))
  add(itemize(vapply(talks, function(t) {
    m <- t$meta
    when <- format(as.Date(as.character(m$date)), "%B %Y")
    paste0(
      quoted(m$title, period = TRUE), " ",
      tex_escape(m$venue), ", ",
      tex_escape(m$location), ", ",
      tex_escape(when), "."
    )
  }, character(1))))
}


# ---- research experience ---------------------------------------------------

add(section("Research Experience"))
for (r in cv$research_experience) {
  block <- paste0(
    "\\textbf{", tex_escape(r$role), "}, ", tex_escape(r$institution), "\\\\\n",
    "\\textit{", tex_escape(r$dates), "}\\\\\n",
    if (!is.null(r$supervisor)) paste0("Supervisor: ", tex_escape(r$supervisor), "\\\\\n") else "",
    tex_escape(r$topics)
  )
  add(samepage(block))
}


# ---- teaching (from _teaching/) --------------------------------------------
# Semester comes from the filename (2025_fall_teaching.md), which is exact --
# the `date` field puts the summer pre-course in August and would misread.

teaching <- collection("_teaching")

semester_of <- function(path) {
  m <- regmatches(basename(path), regexec("^(\\d{4})_(fall|spring|summer)_", basename(path)))[[1]]
  if (length(m) < 3) return(NA_character_)
  paste0(toupper(substring(m[3], 1, 1)), substring(m[3], 2), " ", m[2])
}

sort_key <- function(path) {
  m <- regmatches(basename(path), regexec("^(\\d{4})_(fall|spring|summer)_", basename(path)))[[1]]
  if (length(m) < 3) return(0)
  as.numeric(m[2]) + c(spring = 0.1, summer = 0.2, fall = 0.3)[[m[3]]]
}

teaching <- teaching[order(vapply(teaching, function(t) sort_key(t$path), numeric(1)),
                           decreasing = TRUE)]

add(section("Teaching Experience"))
for (t in teaching) {
  # The body's H1 carries the course code and instructor:
  #   # PSCI 2300: Quantitative Political Science I: Computing (Prof. Brenton Kenkel)
  h1 <- grep("^#\\s+", t$body, value = TRUE)[1]
  heading <- trimws(sub("^#\\s+", "", h1 %||% t$meta$title))

  # Split off a trailing "(Prof. Name)" or "(co-taught with Name)" parenthetical.
  paren <- regmatches(heading, regexec("^(.*?)\\s*\\(([^()]*)\\)\\s*$", heading))[[1]]
  course <- if (length(paren) == 3) trimws(paren[2]) else heading
  who    <- if (length(paren) == 3) trimws(paren[3]) else NA_character_

  line <- paste0(tex_escape(t$meta$type), ", ", tex_escape(t$meta$venue))
  if (!is.na(who)) line <- paste0(line, " (", tex_escape(who), ")")

  add(samepage(paste0(
    "\\textbf{", tex_escape(course), "} \\hfill ",
    tex_escape(semester_of(t$path)), "\\\\\n",
    line
  )))
}


# ---- remaining hand-written sections ---------------------------------------

add(section("Fellowships and Grants"))
add(itemize(tex_escape(unlist(cv$fellowships))))

add(section("Workshops and Seminars"))
add(itemize(vapply(cv$workshops, function(w) {
  s <- paste0("\\textbf{", tex_escape(w$name), "}")
  if (!is.null(w$venue)) s <- paste0(s, ", ", tex_escape(w$venue))
  paste0(s, " -- \\textit{", tex_escape(w$role), "} (", tex_escape(w$dates), ")")
}, character(1))))

add(section("Skills"))
add(itemize(vapply(cv$skills, function(s) {
  paste0("\\textbf{", tex_escape(s$label), "}: ", tex_escape(s$items))
}, character(1))))

add(section("Service"))
add(itemize(tex_escape(unlist(cv$service))))

add(section("References"))
add(paste0(tex_escape(cv$references), "\n"))

add("\\end{document}")


# ---- write -----------------------------------------------------------------

target <- file.path(root, "cv", "cv.tex")
writeLines(out, target, useBytes = TRUE)
cat("Wrote", target, "\n")
cat(sprintf("  %d papers, %d talks, %d teaching entries\n",
            length(papers), length(talks), length(teaching)))
